import Link from 'next/link';
import {siteInfo} from '../../../data/site';
import BreadcrumbJsonLd from '../../../components/BreadcrumbJsonLd';
import SiteImage from '../../../components/SiteImage';
export const metadata={title:'린M 패키지 20~25% 할인 | 서버별 구매 안내',description:'린M 패키지와 한정 상품의 구성품·구매 조건을 확인하고 구매 가능한 린M 관련 상품을 서버별 최소 20%부터 최대 25% 할인 상담할 수 있습니다.',keywords:['린M 패키지','린M 패키지 할인','린M 20% 할인','린M 25% 할인','린M 서버별 할인'],alternates:{canonical:'/rinm/package'}};
const checks=[['상품명','비슷한 패키지를 구분하려면 정확한 상품명을 먼저 확인합니다.'],['가격·요구 재화','원화 결제인지 게임 내 재화를 사용하는지 화면에서 확인합니다.'],['구성품','포함된 재화와 성장 재료의 종류·수량을 함께 비교합니다.'],['구매 제한','계정·캐릭터별 구매 횟수 제한이 표시되는지 확인합니다.'],['판매 기간','한정 상품은 시작·종료 시점을 확인해야 합니다.'],['추가 혜택','프로모션이나 첫 구매 혜택은 시점·계정 상태에 따라 달라질 수 있습니다.']];
export default function PackagePage(){return <>
<BreadcrumbJsonLd items={[{name:'홈',href:'/'},{name:'린M',href:'/rinm'},{name:'린M 패키지',href:'/rinm/package'}]}/>
<section className="subhero container"><div><span className="eyebrow">린M 패키지 · 할인 구매</span><h1>패키지 구성은 꼼꼼하게,<br/><span style={{color:'#ffda84'}}>구매 가능 상품은 20~25% 할인</span></h1><p>패키지는 가격만 보는 것보다 구성품·구매 제한·판매 기간을 함께 확인해야 합니다. 몽땅 다이아에서 구매 가능한 린M 관련 상품은 서버와 상품 조건에 따라 <b style={{color:'#fff'}}>최소 20%부터 최대 25%</b> 범위로 할인 판매가를 안내합니다.</p><div className="hero-actions"><a className="btn primary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">패키지 할인 문의</a><Link className="btn secondary" href="/rinm/discount">할인 기준 보기</Link></div><div className="trust-row"><span>최소 20% 할인</span><span>최대 25% 할인</span><span>서버별 차등 적용</span><span>구매 전 판매가 확인</span></div></div><SiteImage src="/images/package/package-hero.webp" alt="린M 패키지 20~25% 할인 구매 대표 이미지" priority/></section>
<section className="section container"><div className="section-head"><span className="eyebrow">패키지 체크리스트</span><h2>할인율과 함께 구매 조건도 확인하세요</h2><p className="section-desc">할인폭이 크더라도 필요한 구성품인지, 구매 제한과 판매 기간이 맞는지 확인해야 실제 구매 효율을 판단하기 쉽습니다.</p></div><div className="card-grid three">{checks.map(([t,d])=><article className="feature-card" key={t}><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section className="section container" style={{paddingTop:'20px'}}><div className="section-head"><span className="eyebrow">서버별 할인 구매</span><h2>패키지 확인 → 서버 확인 → 최종 판매가 안내</h2></div><div className="card-grid three"><article className="feature-card"><span className="eyebrow">01</span><h3>원하는 상품 확인</h3><p>구매하려는 패키지나 린M 관련 상품의 정확한 명칭과 구성 조건을 확인합니다.</p></article><article className="feature-card"><span className="eyebrow">02</span><h3>서버·판매 조건 확인</h3><p>서버와 상품 조건을 확인해 현재 적용할 수 있는 할인율을 확인합니다.</p></article><article className="feature-card"><span className="eyebrow">03</span><h3>20~25% 할인 판매가</h3><p>적용 가능한 할인율과 최종 판매가를 구매 전에 안내합니다.</p></article></div><div className="center-action"><a className="btn primary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">내 서버 패키지 할인 확인</a></div></section>
<section className="section container split-section"><SiteImage className="content-image-slot" src="/images/package/package-content-01.webp" alt="린M 패키지 구성품 안내 이미지"/><div><span className="eyebrow">현재 확인된 상점 구조</span><h2>한정 할인·재료·특수 아이템을 구분해서 확인</h2><p>제공받은 게임 화면에는 한정 할인, 재료, 특수 아이템 등의 상점 분류가 확인됩니다. 실제 구매하려는 상품을 확인한 뒤 서버별 할인 판매 가능 여부를 상담하면 됩니다.</p><Link className="text-link" href="/rinm/items">린M 아이템 정보 →</Link><br/><Link className="text-link" href="/rinm/discount">20~25% 할인 기준 →</Link></div></section>
<section className="section container"><div className="section-head"><span className="eyebrow">구매 신뢰 기준</span><h2>할인율과 최종 판매가를 구분해 안내</h2></div><div className="card-grid three"><article className="feature-card"><h3>서버별 차등 할인</h3><p>모든 상품에 동일한 할인율을 표시하지 않고 서버와 판매 조건을 확인한 뒤 실제 적용 할인율을 안내합니다.</p></article><article className="feature-card"><h3>최종 판매가 사전 확인</h3><p>구매 진행 전에 할인율과 최종 판매가를 확인할 수 있도록 상담합니다.</p></article><article className="feature-card"><h3>확인되지 않은 상품 미표기</h3><p>현재 확보된 자료로 확인되지 않는 패키지명이나 구성품을 임의로 만들어 표시하지 않습니다.</p></article></div></section>
<p className="notice-box container">※ 할인율은 서버·상품·판매 조건에 따라 차등 적용되며 현재 운영 기준은 최소 20%부터 최대 25% 범위입니다. 특정 패키지의 효율이나 추천 순위는 확인 가능한 자료가 충분할 때 별도로 안내합니다.</p>
</>}
