import Link from 'next/link';
import {siteInfo} from '../../../data/site';
import BreadcrumbJsonLd from '../../../components/BreadcrumbJsonLd';
import SiteImage from '../../../components/SiteImage';

export const metadata={title:'린M 다이아 정보·20~25% 할인 구매 안내',description:'린M 다이아, 귀속 다이아, 린M 코인 등 게임 재화를 구분하고 린M 관련 상품의 서버별 최소 20%~최대 25% 할인 구매 상담 방법을 안내합니다.',keywords:['린M 다이아','린M 귀속 다이아','린M 코인','린M 다이아 할인','린M 20% 할인','린M 25% 할인'],alternates:{canonical:'/rinm/diamond'}};
const currencies=[['다이아','게임 상점 화면에서 확인된 주요 재화입니다.'],['귀속 다이아','일반 다이아와 별도로 표시되는 귀속 재화입니다.'],['린M 코인','확보한 공식 안내에서 웹페이지 결제 후 지급되는 재화로 확인됩니다.'],['골드','라운지 이벤트 보상 등에서 실제 명칭이 확인된 게임 내 재화입니다.']];
export default function DiamondPage(){return <>
<BreadcrumbJsonLd items={[{name:'홈',href:'/'},{name:'린M',href:'/rinm'},{name:'린M 다이아',href:'/rinm/diamond'}]}/>
<section className="subhero container"><div><span className="eyebrow">린M 다이아 · 재화 안내</span><h1>다이아 종류는 정확하게,<br/><span style={{color:'#ffda84'}}>관련 상품은 20~25% 할인</span></h1><p>다이아·귀속 다이아·린M 코인처럼 이름이 비슷한 재화는 실제 확인된 자료를 기준으로 구분합니다. 구매 가능한 린M 관련 상품은 서버와 상품 조건에 따라 <b style={{color:'#fff'}}>최소 20%부터 최대 25%</b> 범위로 할인 상담을 진행합니다.</p><div className="hero-actions"><a className="btn primary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">내 서버 할인 문의</a><Link className="btn secondary" href="/rinm/discount">할인 기준 확인</Link></div><div className="trust-row"><span>재화 명칭 구분</span><span>최소 20% 할인</span><span>최대 25% 할인</span><span>서버별 차등 적용</span></div></div><SiteImage src="/images/charge/diamond-hero.webp" alt="린M 다이아와 귀속 다이아 대표 이미지" priority/></section>
<section className="section container"><div className="section-head"><span className="eyebrow">재화 구분</span><h2>현재 자료에서 확인된 4가지 재화</h2><p className="section-desc">상품 구매 전에 어떤 재화와 상품을 원하는지 구분하면 서버별 판매 가능 여부와 할인 조건을 더 정확하게 확인할 수 있습니다.</p></div><div className="card-grid two">{currencies.map(([t,d])=><article className="feature-card" key={t}><h2 className="card-title">{t}</h2><p>{d}</p></article>)}</div><p className="notice-box">공식 안내 자료에는 린M 코인이 <b>1코인 = 100KRW</b> 가치로 안내되어 있습니다. 지급량·추가 증정·프로모션 조건은 시점에 따라 달라질 수 있으며, 몽땅 다이아의 할인율 역시 서버·상품·판매 조건에 따라 차등 적용됩니다.</p></section>
<section className="section container" style={{paddingTop:'20px'}}><div className="section-head"><span className="eyebrow">할인 구매 기준</span><h2>재화 정보 확인 후 서버별 판매가 상담</h2></div><div className="card-grid three"><article className="feature-card"><span className="eyebrow">STEP 01</span><h3>상품·재화 확인</h3><p>구매하려는 린M 상품과 필요한 재화를 먼저 확인합니다.</p></article><article className="feature-card"><span className="eyebrow">STEP 02</span><h3>서버 확인</h3><p>대상 서버를 확인해 현재 적용 가능한 할인 조건을 확인합니다.</p></article><article className="feature-card"><span className="eyebrow">STEP 03</span><h3>20~25% 할인 안내</h3><p>서버와 상품 조건에 맞는 최종 할인율과 판매가를 구매 전에 안내합니다.</p></article></div><div className="center-action"><a className="btn primary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">카카오톡으로 할인 판매가 확인</a></div></section>
<section className="section container"><div className="section-head"><span className="eyebrow">공식 안내에서 확인된 흐름</span><h2>웹 결제 후 게임에서 확인하는 순서</h2></div><div className="card-grid three"><article className="feature-card"><h3>1. 서버·캐릭터 확인</h3><p>결제 전에 대상 서버와 캐릭터 정보가 맞는지 먼저 확인합니다.</p></article><article className="feature-card"><h3>2. 린M 코인 지급 확인</h3><p>확보한 공식 공지에서는 웹페이지 결제 시 린M 코인으로 지급되는 구조가 안내되어 있습니다.</p></article><article className="feature-card"><h3>3. 상점 → 충전 확인</h3><p>공식 안내에는 결제 후 게임 내 상점 → 충전에서 확인하는 흐름이 제시되어 있습니다.</p></article></div></section>
<section className="section container split-section"><SiteImage className="content-image-slot" src="/images/charge/diamond-content.webp" alt="린M 게임 재화 안내 이미지"/><div><span className="eyebrow">구매 전 확인</span><h2>정상가와 서버별 할인 판매가를 함께 비교</h2><p>이 페이지에서는 재화의 차이를 먼저 확인하고, 실제 구매를 원하는 경우 충전·할인 페이지에서 정상가와 할인 기준을 비교할 수 있습니다. 최종 판매가는 서버 확인 후 상담에서 안내합니다.</p><Link className="text-link" href="/rinm/charge">린M 충전 정상가 보기 →</Link><br/><Link className="text-link" href="/rinm/discount">20~25% 할인 기준 보기 →</Link></div></section>
</>}
