import Link from 'next/link';
import {siteInfo} from '../../../data/site';
import BreadcrumbJsonLd from '../../../components/BreadcrumbJsonLd';
import FaqJsonLd from '../../../components/FaqJsonLd';
import SiteImage from '../../../components/SiteImage';
export const metadata={title:'린M 충전 20~25% 할인 | 서버별 판매가 안내',description:'린M 60부터 6480까지 충전 단위와 정상가를 확인하고 서버별 최소 20%부터 최대 25% 할인 판매가를 상담할 수 있습니다.',keywords:['린M 충전','린M 할인 충전','린M 20% 할인','린M 25% 할인','린M 서버별 할인'],alternates:{canonical:'/rinm/charge'}};
const products=[['60','1,500원'],['300','7,500원'],['680','15,000원'],['980','22,000원'],['1,280','30,000원'],['1,980','45,000원'],['3,280','75,000원'],['6,480','149,000원']];
const faqs=[{q:'린M 상품은 얼마나 할인되나요?',a:'서버와 상품 조건에 따라 할인율이 달라지며 현재 운영 기준은 최소 20%부터 최대 25% 범위입니다. 구매 전 서버를 확인한 뒤 최종 할인율과 판매가를 안내합니다.'},{q:'표시된 가격은 할인 판매가인가요?',a:'상품 카드의 금액은 비교를 위한 게임 화면 기준 정상가입니다. 실제 판매가는 서버별 적용 할인율을 확인한 뒤 상담에서 안내합니다.'},{q:'첫 충전 혜택은 항상 적용되나요?',a:'첫 충전 또는 첫 구매 혜택은 계정 상태와 시점에 따라 달라질 수 있어 구매 전 확인이 필요합니다.'},{q:'상담 전에 무엇을 준비하면 되나요?',a:'원하는 충전 단위와 서버, 캐릭터 또는 캐릭터 ID를 확인하면 됩니다. 계정 비밀번호나 결제 비밀번호는 전달하지 않습니다.'}];
export default function ChargePage(){return <>
<BreadcrumbJsonLd items={[{name:'홈',href:'/'},{name:'린M',href:'/rinm'},{name:'린M 충전',href:'/rinm/charge'}]}/><FaqJsonLd items={faqs}/>
<section className="subhero container charge-hero"><div><span className="eyebrow">린M 할인 충전 · 몽땅 다이아</span><h1>린M 충전 상품<br/><span style={{color:'#ffda84'}}>20% ~ 25% 할인</span></h1><p>게임 화면 기준 정상가를 먼저 확인하고, 서버에 따라 <b style={{color:'#fff'}}>최소 20%부터 최대 25%</b> 범위의 할인 판매가를 안내합니다. 서버·상품·판매 조건에 따라 실제 적용 할인율은 달라질 수 있습니다.</p><div className="hero-actions"><a className="btn primary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">내 서버 할인율 확인</a><Link className="btn secondary" href="/rinm/discount">할인 기준 보기</Link></div><div className="trust-row"><span>최소 20% 할인</span><span>최대 25% 할인</span><span>서버별 차등 적용</span><span>사업자 정보 공개</span></div></div><SiteImage src="/images/charge/charge-hero.webp" alt="린M 20~25% 할인 충전 대표 이미지" priority/></section>
<section className="section container"><div className="section-head"><span className="eyebrow">충전 상품 정상가</span><h2>원하는 단위를 고르고 할인 판매가를 확인하세요</h2><p className="section-desc">아래 금액은 비교 기준이 되는 게임 화면 정상가입니다. 상품을 선택한 뒤 서버를 알려주시면 현재 적용 가능한 할인율과 최종 판매가를 안내합니다.</p></div><div className="price-grid">{products.map(([a,p])=><Link className="price-card product-card" href={`/order?amount=${encodeURIComponent(a)}`} key={a}><div className="product-badge">20~25% 할인</div><strong>{a}</strong><span>충전 단위</span><b>{p}</b><small>게임 화면 기준 정상가</small><em className="price-cta">서버별 할인 판매가 문의 →</em></Link>)}</div><p className="notice-box">※ 할인율은 서버·상품·판매 조건에 따라 차등 적용됩니다. 현재 운영 기준은 최소 20%부터 최대 25% 범위이며 구매 전 최종 할인율과 판매가를 확인해 주세요.</p></section>
<section className="section container" style={{paddingTop:'20px'}}><div className="section-head"><span className="eyebrow">할인 적용 방식</span><h2>정상가보다 얼마나 절약되는지 먼저 확인</h2></div><div className="card-grid three"><article className="feature-card"><span className="eyebrow">20% 할인 예시</span><h3>75,000원 → 60,000원</h3><p>정상가 75,000원을 기준으로 20% 할인이 적용될 경우 15,000원을 절약하는 계산 예시입니다.</p></article><article className="feature-card"><span className="eyebrow">25% 할인 예시</span><h3>75,000원 → 56,250원</h3><p>동일 정상가에 25% 할인이 적용될 경우 18,750원을 절약하는 계산 예시입니다.</p></article><article className="feature-card"><span className="eyebrow">실제 구매가</span><h3>서버 확인 후 확정</h3><p>예시 금액은 할인 구조를 설명하기 위한 계산값이며 실제 판매가는 서버와 상품 조건 확인 후 안내합니다.</p></article></div></section>
<section className="section container purchase-flow"><div className="section-head"><span className="eyebrow">할인 구매 과정</span><h2>서버 확인부터 판매가 안내까지 3단계</h2></div><div className="flow-line"><article><b>01</b><h3>상품 선택</h3><p>필요한 충전 단위를 선택합니다.</p></article><article><b>02</b><h3>서버 확인</h3><p>서버와 캐릭터 정보를 확인해 적용 가능한 할인 조건을 확인합니다.</p></article><article><b>03</b><h3>할인 판매가 안내</h3><p>20~25% 범위에서 현재 적용 할인율과 최종 판매가를 안내합니다.</p></article></div><div className="center-action"><a className="btn primary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">카카오톡으로 할인 문의</a></div></section>
<section className="section container split-section"><SiteImage className="content-image-slot" src="/images/charge/charge-content-01.webp" alt="린M 모바일 상점과 충전 안내 이미지"/><div><span className="eyebrow">가격 확인 기준</span><h2>정상가와 할인 판매가를 구분해서 안내</h2><p>게임 화면에서 확인한 정상가는 비교 기준으로 공개하고, 몽땅 다이아의 실제 판매가는 서버 확인 후 안내합니다. 정상가와 최종 판매가를 구분하면 이용자가 실제 절감 금액을 직접 비교할 수 있습니다.</p><Link className="text-link" href="/rinm/discount">린M 할인 기준 자세히 보기 →</Link></div></section>
<section className="section container"><div className="section-head"><span className="eyebrow">신뢰 기준</span><h2>할인율만큼 구매 과정도 명확하게</h2></div><div className="card-grid three"><article className="feature-card"><h3>사업자 정보 공개</h3><p>푸터에서 상호, 대표자, 사업자등록번호, 통신판매업 신고정보와 연락처를 확인할 수 있습니다.</p></article><article className="feature-card"><h3>최종 가격 사전 안내</h3><p>서버별 적용 할인율과 최종 판매가를 구매 진행 전에 확인할 수 있도록 안내합니다.</p></article><article className="feature-card"><h3>민감정보 미요청</h3><p>문의 단계에서 게임 계정 비밀번호나 결제 비밀번호를 입력받지 않습니다.</p></article></div></section>
<section className="section container"><div className="section-head"><span className="eyebrow">자주 묻는 질문</span><h2>린M 할인 충전 문의 전 확인</h2></div><div className="card-grid two">{faqs.map(x=><article className="feature-card" key={x.q}><h3>{x.q}</h3><p>{x.a}</p></article>)}</div></section>
</>}
