import Link from 'next/link';
import {siteInfo} from '../../../data/site';
import BreadcrumbJsonLd from '../../../components/BreadcrumbJsonLd';
import FaqJsonLd from '../../../components/FaqJsonLd';
export const metadata={title:'린M 충전 가격·할인 구매 안내',description:'린M 60부터 6480까지 충전 단위와 게임 상점 정상가, 첫 충전 확인사항, 서버·캐릭터 확인과 몽땅 다이아 구매 상담 흐름을 안내합니다.',alternates:{canonical:'/rinm/charge'}};
const products=[['60','1,500원'],['300','7,500원'],['680','15,000원'],['980','22,000원'],['1,280','30,000원'],['1,980','45,000원'],['3,280','75,000원'],['6,480','149,000원']];
const faqs=[{q:'린M 충전 가격은 얼마인가요?',a:'현재 표시 가격은 제공받은 실제 게임 충전 화면에서 확인한 정상가입니다. 몽땅 다이아 판매가는 판매 정책 확정 후 별도로 표시합니다.'},{q:'첫 충전 혜택은 항상 적용되나요?',a:'게임 화면에는 첫 충전 또는 첫 구매 관련 혜택이 표시되지만 계정 상태와 시점에 따라 달라질 수 있어 구매 전 확인이 필요합니다.'},{q:'상담 전에 무엇을 준비하면 되나요?',a:'원하는 충전 단위와 서버, 캐릭터 또는 캐릭터 ID를 확인하면 됩니다. 계정 비밀번호나 결제 비밀번호는 전달하지 않습니다.'},{q:'사이트에서 바로 결제하나요?',a:'현재 사이트에서는 직접 결제하지 않고 상품을 선택한 뒤 카카오톡 또는 전화로 구매 상담을 진행합니다.'}];
export default function ChargePage(){return <>
<BreadcrumbJsonLd items={[{name:'홈',href:'/'},{name:'린M',href:'/rinm'},{name:'린M 충전',href:'/rinm/charge'}]}/><FaqJsonLd items={faqs}/>
<section className="subhero container charge-hero"><div><span className="eyebrow">린M 충전 · 몽땅 다이아</span><h1>충전 단위와 정상가를 확인하고 할인 판매가 문의</h1><p>60부터 6,480까지 실제 게임 화면에서 확인한 상품을 기준으로 정리했습니다. 필요한 단위를 선택하면 구매 문의 화면으로 바로 이동합니다.</p><div className="hero-actions"><Link className="btn primary" href="/order">구매 문의 준비</Link><a className="btn secondary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">카카오톡 {siteInfo.kakaoId}</a></div><div className="trust-row"><span>정상가 공개</span><span>사업자 정보 공개</span><span>비밀번호 요청 안 함</span></div></div><div className="image-slot"><span>/public/images/charge/hero.webp</span></div></section>
<section className="section container"><div className="section-head"><span className="eyebrow">충전 상품</span><h2>원하는 단위를 선택하세요</h2><p className="section-desc">상품 카드를 누르면 선택한 충전 단위가 구매 문의 화면으로 전달됩니다.</p></div><div className="price-grid">{products.map(([a,p])=><Link className="price-card product-card" href={`/order?amount=${encodeURIComponent(a)}`} key={a}><div className="product-badge">린M</div><strong>{a}</strong><span>충전 단위</span><b>{p}</b><small>게임 화면 기준 정상가</small><em className="price-cta">이 상품 문의하기 →</em></Link>)}</div><p className="notice-box">※ 몽땅 다이아 실제 판매가·할인율은 확정 후 별도 표시합니다. 프로모션 및 첫 충전 혜택은 계정 상태와 시점에 따라 달라질 수 있습니다.</p></section>
<section className="section container purchase-flow"><div className="section-head"><span className="eyebrow">구매 문의 과정</span><h2>복잡하지 않게 3단계로</h2></div><div className="flow-line"><article><b>01</b><h3>상품 선택</h3><p>필요한 충전 단위를 선택합니다.</p></article><article><b>02</b><h3>정보 확인</h3><p>서버와 캐릭터 또는 캐릭터 ID를 확인합니다.</p></article><article><b>03</b><h3>판매가 상담</h3><p>카카오톡 pay3810 또는 전화로 현재 판매가와 가능 여부를 확인합니다.</p></article></div><div className="center-action"><Link className="btn primary" href="/order">지금 구매 문의 준비</Link></div></section>
<section className="section container split-section"><div className="image-slot content-image-slot"><span>/public/images/charge/content-01.webp</span></div><div><span className="eyebrow">게임 내 확인</span><h2>웹 결제 관련 공식 안내는 상점 → 충전 확인</h2><p>확보한 공식 라운지 자료에서는 웹페이지 결제 후 린M 코인으로 지급되고 게임 내 <b>상점 → 충전</b>에서 확인하는 흐름이 안내되어 있습니다. 해당 정보는 별도 충전 가이드에서 자세히 분리합니다.</p><Link className="text-link" href="/rinm/guide/charge">린M 충전 방법 보기 →</Link></div></section>
<section className="section container"><div className="section-head"><span className="eyebrow">안전한 상담</span><h2>상담할 때 전달하지 않아도 되는 정보</h2></div><div className="card-grid three"><article className="feature-card"><h3>계정 비밀번호</h3><p>현재 구매 문의 폼에서는 게임 계정 비밀번호를 입력받지 않습니다.</p></article><article className="feature-card"><h3>결제 비밀번호</h3><p>카드·간편결제 등의 결제 비밀번호를 사이트에 입력하지 않습니다.</p></article><article className="feature-card"><h3>불필요한 개인정보</h3><p>현재 문의 단계에서는 상품 상담에 필요한 최소 정보만 정리하도록 구성했습니다.</p></article></div></section>
<section className="section container"><div className="section-head"><span className="eyebrow">자주 묻는 질문</span><h2>린M 충전 문의 전 확인</h2></div><div className="card-grid two">{faqs.map(x=><article className="feature-card" key={x.q}><h3>{x.q}</h3><p>{x.a}</p></article>)}</div></section>
</>}
