import Link from 'next/link';
import BreadcrumbJsonLd from '../../../../components/BreadcrumbJsonLd';
import SiteImage from '../../../../components/SiteImage';
export const metadata={title:'린M 초보 가이드·상점·재화 안내',description:'린M을 처음 시작할 때 알아둘 재화, 상점 메뉴, 주요 아이템과 충전 확인 순서를 쉽게 정리했습니다. 구매 가능한 상품은 서버에 따라 최소 20%부터 최대 25%까지 할인됩니다.',keywords:['린M','린M 초보'],alternates:{canonical:'/rinm/guide/beginner'}};
export default function BeginnerPage(){return <>
<BreadcrumbJsonLd items={[{name:'홈',href:'/'},{name:'린M',href:'/rinm'},{name:'공략',href:'/rinm/guide'},{name:'초보',href:'/rinm/guide/beginner'}]}/>
<section className="subhero container"><div><span className="eyebrow">린M 초보</span><h1>처음이라면 재화 → 상점 → 아이템 순서로</h1><p>복잡한 공략부터 외우기보다 현재 게임 화면에서 확인되는 기본 구조를 먼저 익히도록 구성했습니다.</p></div><SiteImage src="/images/guide/beginner-hero.webp" alt="린M 초보 모험 시작 이미지" priority/></section>
<section className="section container"><div className="section-head"><span className="eyebrow">초보 4단계</span><h2>게임 화면을 이해하는 기본 순서</h2></div><div className="card-grid four"><article className="feature-card"><h3>1. 재화 구분</h3><p>다이아·귀속 다이아·린M 코인·골드처럼 실제 확인된 재화부터 서로 구분합니다.</p></article><article className="feature-card"><h3>2. 상점 메뉴</h3><p>귀족 상점, 재료, 특수 아이템, 한정 할인, 미네랄 교환, 잡화, 레저 상점 등 확인된 메뉴를 살펴봅니다.</p></article><article className="feature-card"><h3>3. 아이템 명칭</h3><p>신기석, 각종 수정, 마법석, 미네랄, 탈것 영혼, 날개 광휘, 보물지도 등 실제 명칭을 익힙니다.</p></article><article className="feature-card"><h3>4. 충전 확인</h3><p>충전이 필요하다면 상품 단위와 혜택, 서버·캐릭터 정보를 먼저 확인합니다.</p></article></div></section>
<section className="section container"><div className="section-head"><span className="eyebrow">다음에 볼 페이지</span><h2>목적에 따라 필요한 정보만 이어서</h2></div><div className="card-grid three"><Link className="feature-card" href="/rinm/diamond"><h3>재화가 헷갈릴 때</h3><p>다이아·귀속 다이아·린M 코인의 확인된 차이를 봅니다.</p></Link><Link className="feature-card" href="/rinm/items"><h3>아이템을 찾을 때</h3><p>상점 화면에서 확인된 아이템을 분류별로 봅니다.</p></Link><Link className="feature-card" href="/rinm/guide/growth"><h3>육성을 시작할 때</h3><p>성장 관련 재료와 아이템 명칭을 이어서 확인합니다.</p></Link></div></section>
<section className="section container split-section"><SiteImage className="content-image-slot" src="/images/guide/beginner-content.webp" alt="린M 초보 상점과 재화 안내 이미지"/><div><span className="eyebrow">주의</span><h2>초보 추천 수치나 최적 루트는 아직 확정하지 않습니다</h2><p>현재 제공된 자료는 상점과 재화·아이템 구조를 이해하기에는 충분하지만 레벨별 최적 육성 루트나 효율 순위를 판단하기에는 부족합니다. 해당 자료가 확보되면 별도 가이드에서 보강합니다.</p></div></section>
</>}
