import Link from 'next/link';
import {siteInfo} from '../data/site';
import SiteImage from '../components/SiteImage';
const quick=[['린M 충전','/rinm/charge','서버별 할인율 확인·충전 상담'],['린M 할인','/rinm/discount','최소 20% ~ 최대 25% 할인 안내'],['린M 다이아','/rinm/diamond','다이아·귀속 다이아·린M 코인'],['린M 패키지','/rinm/package','패키지·한정 할인 정보'],['린M 아이템','/rinm/items','상점 아이템·재화'],['린M 신격','/rinm/guide/shingyeok','추천·조합·티어 자료 준비'],['린M 초보','/rinm/guide/beginner','재화부터 시작하는 초보 가이드'],['린M 게임정보','/rinm/news','공지·업데이트·이벤트']];
const prices=[['60','1,500원'],['300','7,500원'],['680','15,000원'],['980','22,000원'],['1,280','30,000원'],['1,980','45,000원'],['3,280','75,000원'],['6,480','149,000원']];
export default function HomePage(){return <>
<section className="hero hero-home"><div className="container hero-copy"><span className="eyebrow">린M 서버별 할인 판매 · 몽땅 다이아</span><h1>린M 상품<br/><span style={{color:'#ffda84'}}>20% ~ 25% 할인</span></h1><p><b style={{color:'#fff'}}>각 서버별 할인율을 차등 적용하며 최소 20%부터 최대 25%까지 할인 판매합니다.</b> 서버와 상품에 따라 적용 할인율이 달라질 수 있어 구매 전 실제 판매가를 투명하게 안내해드립니다.</p><div style={{display:'flex',flexWrap:'wrap',gap:'10px',marginTop:'18px'}}><span style={{padding:'8px 12px',border:'1px solid #806c43',borderRadius:'999px',background:'#211b12',color:'#ffda84',fontWeight:900}}>최소 20% 할인</span><span style={{padding:'8px 12px',border:'1px solid #806c43',borderRadius:'999px',background:'#211b12',color:'#ffda84',fontWeight:900}}>최대 25% 할인</span><span style={{padding:'8px 12px',border:'1px solid #3b4250',borderRadius:'999px',background:'#11151c',color:'#d7dbe5',fontWeight:700}}>서버별 차등 적용</span></div><div className="hero-actions"><Link className="btn primary" href="/rinm/discount">내 서버 할인율 확인</Link><a className="btn secondary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">카카오톡 할인 문의</a></div><div className="trust-row"><span>사업자 정보 공개</span><span>구매 전 할인율 안내</span><span>서버별 판매가 확인</span><span>전화·카카오톡 상담</span></div></div><SiteImage className="hero-image-slot" src="/images/home/home-hero.webp" alt="린M 서버별 20%에서 25% 할인 판매를 안내하는 몽땅 다이아 메인 이미지" priority/></section>

<section className="section container" style={{paddingTop:'44px',paddingBottom:'20px'}}><div style={{border:'1px solid #5d4b28',borderRadius:'22px',padding:'28px',background:'linear-gradient(135deg,#1a1710,#11141b)',boxShadow:'0 18px 50px rgba(0,0,0,.2)'}}><span className="eyebrow">몽땅 다이아 할인 기준</span><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(210px,1fr))',gap:'16px',alignItems:'stretch'}}><div style={{padding:'22px',borderRadius:'16px',background:'#11151c',border:'1px solid #343b49'}}><strong style={{display:'block',fontSize:'2.1rem',color:'#ffda84'}}>20%</strong><b>최소 할인</b><p style={{margin:'8px 0 0',color:'#aeb5c2'}}>서버별 조건에 따라 최소 20% 할인부터 적용합니다.</p></div><div style={{padding:'22px',borderRadius:'16px',background:'#11151c',border:'1px solid #6b5730'}}><strong style={{display:'block',fontSize:'2.1rem',color:'#ffda84'}}>25%</strong><b>최대 할인</b><p style={{margin:'8px 0 0',color:'#aeb5c2'}}>적용 가능한 서버·상품은 최대 25% 할인 판매합니다.</p></div><div style={{padding:'22px',borderRadius:'16px',background:'#11151c',border:'1px solid #343b49'}}><strong style={{display:'block',fontSize:'1.35rem',color:'#fff'}}>서버별 차등</strong><b>구매 전 실판매가 확인</b><p style={{margin:'8px 0 0',color:'#aeb5c2'}}>할인율을 일괄 표시하지 않고 서버와 상품을 확인한 뒤 적용 가격을 안내합니다.</p></div></div><p style={{margin:'18px 0 0',color:'#8f97aa',fontSize:'.9rem'}}>※ 실제 할인율은 서버·상품·판매 조건에 따라 달라질 수 있으며, 구매 전 상담을 통해 최종 할인율과 판매가를 확인할 수 있습니다.</p></div></section>

<section className="section container"><div className="section-head"><span className="eyebrow">린M 공식 상점 정상가</span><h2>정상가를 확인하고 할인 구매가를 문의하세요</h2><p className="section-desc">아래 금액은 비교를 위한 게임 상점 정상가입니다. 실제 몽땅 다이아 판매가는 서버별 할인율을 적용해 별도로 안내합니다.</p></div><div className="price-grid compact-price-grid">{prices.map(([a,p])=><Link className="price-card" href={`/order?amount=${encodeURIComponent(a)}`} key={a}><strong>{a}</strong><span>충전 단위</span><b>{p}</b><small>정상가</small><em className="price-cta">20~25% 할인 구매 문의 →</em></Link>)}</div><div className="center-action"><Link className="btn primary" href="/rinm/discount">서버별 할인 안내 보기</Link></div></section>
<section className="section container conversion-strip"><div><span className="eyebrow">할인 구매 3단계</span><h2>서버 확인 → 할인율 안내 → 구매 상담</h2></div><div className="conversion-steps"><div><b>01</b><span>서버·상품 확인</span></div><div><b>02</b><span>20~25% 할인율 안내</span></div><div><b>03</b><span>판매가 확인·상담</span></div></div><Link className="btn primary" href="/order">할인 구매 문의</Link></section>
<section className="section container"><div className="section-head"><span className="eyebrow">린M 정보 허브</span><h2>할인 구매와 실제 게임 정보를 한곳에서</h2></div><div className="card-grid four">{quick.map(([t,h,d])=><Link className="feature-card" href={h} key={h}><h3>{t}</h3><p>{d}</p></Link>)}</div></section>
<section className="section container split-section"><div><span className="eyebrow">서버별 할인 상담</span><h2>카카오톡 pay3810 · 전화 010-6289-3810</h2><p>서버와 구매하려는 상품을 알려주시면 적용 가능한 할인율과 실제 판매가를 먼저 안내합니다. 할인율은 서버별로 차등 적용되며 최소 20%부터 최대 25% 범위에서 적용됩니다.</p><div className="hero-actions"><a className="btn primary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">내 서버 할인 문의</a><a className="btn secondary" href={`tel:${siteInfo.phone.replaceAll('-','')}`}>{siteInfo.phone}</a></div></div><SiteImage className="content-image-slot" src="/images/home/home-charge.webp" alt="린M 서버별 할인 충전 상담 이미지"/></section>
<section className="section container split-section"><SiteImage className="content-image-slot" src="/images/home/home-store.webp" alt="린M 게임 상점 분위기 이미지"/><div><span className="eyebrow">신뢰할 수 있는 가격 안내</span><h2>할인율보다 먼저 실제 결제 금액을 확인하세요</h2><p>몽땅 다이아는 서버별 조건이 다른 점을 명확히 안내하고, 구매 전에 적용 할인율과 최종 판매가를 확인할 수 있도록 운영합니다. 린M 관련 정보 역시 제공받은 실제 게임 화면과 공식 자료에서 확인한 명칭을 우선 사용합니다.</p><Link className="text-link" href="/rinm/discount">할인 기준 자세히 보기 →</Link></div></section>
</>}
