import Link from 'next/link';
import {siteInfo} from '../data/site';
const quick=[['린M 충전','/rinm/charge','충전 단위·정상가·구매 문의'],['린M 할인','/rinm/discount','판매가·할인 비교 준비'],['린M 다이아','/rinm/diamond','다이아·귀속 다이아·린M 코인'],['린M 패키지','/rinm/package','패키지·한정 할인 정보'],['린M 아이템','/rinm/items','상점 아이템·재화'],['린M 신격','/rinm/guide/shingyeok','추천·조합·티어 자료 준비'],['린M 초보','/rinm/guide/beginner','재화부터 시작하는 초보 가이드'],['린M 게임정보','/rinm/news','공지·업데이트·이벤트']];
const prices=[['60','1,500원'],['300','7,500원'],['680','15,000원'],['980','22,000원'],['1,280','30,000원'],['1,980','45,000원'],['3,280','75,000원'],['6,480','149,000원']];
export default function HomePage(){return <>
<section className="hero hero-home"><div className="container hero-copy"><span className="eyebrow">린M 할인 충전 · 몽땅 다이아</span><h1>린M 충전 가격 확인부터<br/>구매 상담까지 빠르게</h1><p>실제 게임 상점 화면에서 확인한 충전 단위와 정상가를 먼저 비교하고, 카카오톡 <b>{siteInfo.kakaoId}</b> 또는 전화로 판매가를 문의할 수 있습니다.</p><div className="hero-actions"><Link className="btn primary" href="/rinm/charge">린M 충전 가격 보기</Link><a className="btn secondary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">카카오톡 할인 문의</a></div><div className="trust-row"><span>사업자 정보 공개</span><span>카카오톡 상담</span><span>전화 상담</span><span>실제 린M 자료 기반</span></div></div><div className="image-slot hero-image-slot"><span>/public/images/home/hero.webp</span></div></section>
<section className="section container"><div className="section-head"><span className="eyebrow">린M 충전 가격</span><h2>게임 화면에서 확인한 정상가</h2><p className="section-desc">현재는 공식 상점 정상가를 먼저 제공합니다. 몽땅 다이아 판매가가 확정되면 정상가와 할인 판매가를 한눈에 비교하도록 표시합니다.</p></div><div className="price-grid compact-price-grid">{prices.map(([a,p])=><Link className="price-card" href={`/order?amount=${encodeURIComponent(a)}`} key={a}><strong>{a}</strong><span>충전 단위</span><b>{p}</b><small>정상가</small><em className="price-cta">구매 문의 →</em></Link>)}</div><div className="center-action"><Link className="btn primary" href="/rinm/charge">전체 충전 안내 보기</Link></div></section>
<section className="section container conversion-strip"><div><span className="eyebrow">구매 상담 3단계</span><h2>상품 선택 → 정보 확인 → 상담</h2></div><div className="conversion-steps"><div><b>01</b><span>충전 단위 선택</span></div><div><b>02</b><span>서버·캐릭터 확인</span></div><div><b>03</b><span>카카오톡·전화 상담</span></div></div><Link className="btn primary" href="/order">구매 문의 준비</Link></section>
<section className="section container"><div className="section-head"><span className="eyebrow">린M 정보 허브</span><h2>구매뿐 아니라 실제 게임 정보까지</h2></div><div className="card-grid four">{quick.map(([t,h,d])=><Link className="feature-card" href={h} key={h}><h3>{t}</h3><p>{d}</p></Link>)}</div></section>
<section className="section container split-section"><div><span className="eyebrow">상담 채널</span><h2>카카오톡 pay3810 · 전화 010-6289-3810</h2><p>가격이나 상품을 확인한 뒤 바로 상담할 수 있습니다. 현재 사이트 주문 화면은 결제나 계정 비밀번호를 받지 않고 상담 내용을 정리하는 용도로만 사용합니다.</p><div className="hero-actions"><a className="btn primary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">카카오톡 문의</a><a className="btn secondary" href={`tel:${siteInfo.phone.replaceAll('-','')}`}>{siteInfo.phone}</a></div></div><div className="image-slot content-image-slot"><span>/public/images/home/charge.webp</span></div></section>
<section className="section container split-section"><div className="image-slot content-image-slot"><span>/public/images/home/store.webp</span></div><div><span className="eyebrow">정보 신뢰 기준</span><h2>리니지M과 섞지 않고 ‘린M’ 자료만 사용</h2><p>다이아, 귀속 다이아, 린M 코인, 신기석, 탈것 영혼, 날개 광휘, 마법석, 미네랄 등 제공받은 실제 게임 화면과 공식 라운지 자료에서 확인한 명칭을 우선 사용합니다.</p><Link className="text-link" href="/rinm">린M 전체 정보 보기 →</Link></div></section>
</>}
