import Link from 'next/link';
import {siteInfo} from '../../../data/site';
import BreadcrumbJsonLd from '../../../components/BreadcrumbJsonLd';
import SiteImage from '../../../components/SiteImage';
export const metadata={title:'린M 아이템 정보·20~25% 할인 구매 안내',description:'린M 실제 상점 화면에서 확인한 신기석, 수정류, 탈것 영혼, 날개 광휘, 마법석 등 아이템을 정리하고 구매 가능한 린M 관련 상품의 서버별 20~25% 할인 상담을 안내합니다.',keywords:['린M 아이템','린M 아이템 할인','린M 상점','린M 20% 할인','린M 25% 할인','린M 서버별 할인'],alternates:{canonical:'/rinm/items'}};
const groups=[{title:'재료·성장',items:['신기석','공명 제련 수정','구슬 수정','홀리 수정','황금 수정','성물 수정','성석 가루']},{title:'탈것·장비 관련',items:['탈것 영혼','날개 광휘','홀리웨폰 축복 오일','펫 장비 조각','영혼의 핵']},{title:'교환·편의',items:['미네랄 주머니','1레벨 마법석 상자','일반 보물지도','고급 보물지도','슈퍼 보물지도','시공 열쇠','명상(6시간)']}];
const shops=['귀족 상점','재료','특수 아이템','한정 할인','미네랄 교환','잡화','레저 상점'];
export default function ItemsPage(){return <>
<BreadcrumbJsonLd items={[{name:'홈',href:'/'},{name:'린M',href:'/rinm'},{name:'린M 아이템',href:'/rinm/items'}]}/>
<section className="subhero container"><div><span className="eyebrow">린M 아이템 · 할인 구매 안내</span><h1>아이템 정보는 정확하게,<br/><span style={{color:'#ffda84'}}>구매 가능 상품은 20~25% 할인</span></h1><p>제공받은 실제 게임 화면에서 명칭이 확인된 아이템부터 분류합니다. 몽땅 다이아에서 구매 가능한 린M 관련 상품은 서버와 상품 조건에 따라 <b style={{color:'#fff'}}>최소 20%부터 최대 25%</b> 범위의 할인 판매가를 안내합니다.</p><div className="hero-actions"><a className="btn primary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">아이템 할인 문의</a><Link className="btn secondary" href="/rinm/discount">20~25% 할인 기준</Link></div><div className="trust-row"><span>실제 확인된 명칭</span><span>최소 20% 할인</span><span>최대 25% 할인</span><span>서버별 차등 적용</span></div></div><SiteImage src="/images/items/items-hero.webp" alt="린M 주요 아이템과 할인 구매 대표 이미지" priority/></section>
<section className="section container"><div className="section-head"><span className="eyebrow">아이템 분류</span><h2>성장 재료부터 보물지도까지</h2><p className="section-desc">검색을 위해 임의의 아이템명을 추가하지 않고 현재 확보된 게임 화면에서 확인 가능한 명칭을 중심으로 정리합니다.</p></div><div className="card-grid three">{groups.map(g=><article className="feature-card" key={g.title}><h2 className="card-title">{g.title}</h2><ul className="keyword-list">{g.items.map(i=><li key={i}>{i}</li>)}</ul></article>)}</div></section>
<section className="section container" style={{paddingTop:'20px'}}><div className="section-head"><span className="eyebrow">할인 구매 흐름</span><h2>상품을 확인했다면 서버별 판매가를 확인하세요</h2></div><div className="card-grid three"><article className="feature-card"><span className="eyebrow">01</span><h3>상품명 확인</h3><p>원하는 린M 상품이나 아이템 관련 상품의 정확한 명칭을 먼저 확인합니다.</p></article><article className="feature-card"><span className="eyebrow">02</span><h3>서버·조건 확인</h3><p>서버와 현재 판매 조건을 확인해 적용 가능한 할인율을 확인합니다.</p></article><article className="feature-card"><span className="eyebrow">03</span><h3>20~25% 할인 판매가</h3><p>최소 20%부터 최대 25% 범위에서 실제 적용 할인율과 최종 판매가를 안내합니다.</p></article></div><div className="center-action"><a className="btn primary" href={siteInfo.kakaoUrl} target="_blank" rel="noreferrer">내 서버 할인 판매가 문의</a></div></section>
<section className="section container"><div className="section-head"><span className="eyebrow">게임 상점 메뉴</span><h2>현재 화면에서 확인된 상점 분류</h2></div><ul className="keyword-list">{shops.map(x=><li key={x}>{x}</li>)}</ul><p className="notice-box">각 아이템의 정확한 효과, 요구 레벨, 교환 비율, 구매 제한 등은 현재 확보한 화면만으로 모두 확정할 수 없습니다. 할인율 또한 서버·상품·판매 조건에 따라 차등 적용되므로 실제 구매 전 최종 판매가를 확인해 주세요.</p></section>
<section className="section container split-section"><SiteImage className="content-image-slot" src="/images/items/items-content-01.webp" alt="린M 상점 아이템 안내 이미지"/><div><span className="eyebrow">구매 전 체크</span><h2>같은 아이템명이라도 판매처와 조건을 함께 확인</h2><p>상점 카테고리, 요구 재화, 구매 제한, 이벤트 기간을 함께 확인해야 합니다. 구매 가능한 상품의 경우 서버까지 확인한 뒤 적용 할인율과 최종 판매가를 안내합니다.</p><Link className="text-link" href="/rinm/guide/growth">린M 육성 가이드 →</Link><br/><Link className="text-link" href="/rinm/guide/equipment">린M 장비 가이드 →</Link><br/><Link className="text-link" href="/rinm/discount">린M 할인 기준 →</Link></div></section>
<section className="section container"><div className="section-head"><span className="eyebrow">신뢰 기준</span><h2>확인 가능한 정보와 판매 조건을 구분합니다</h2></div><div className="card-grid three"><article className="feature-card"><h3>확인된 아이템만 안내</h3><p>실제 화면이나 확보된 자료에서 확인되지 않은 아이템명을 임의로 만들어 추가하지 않습니다.</p></article><article className="feature-card"><h3>서버별 할인율 확인</h3><p>일괄적인 할인율을 단정하지 않고 서버와 상품 조건을 확인해 실제 적용 할인율을 안내합니다.</p></article><article className="feature-card"><h3>구매 전 최종가 확인</h3><p>할인 적용 후 실제 판매가를 구매 전에 확인할 수 있도록 상담합니다.</p></article></div></section>
</>}
